version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
        - "7474:7474"
        - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import
    networks: 
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/mongo/
    networks: 
      - backend

  account-service:
    container_name: account-service
    build: ./services/account/
    ports: 
      - "3000:3000"
    environment:
      - RELATION_DB_URL=bolt://neo4j:7687
      - RELATION_DB_USER=linkedtek-account-service
      - RELATION_DB_PASS=linkedtek
    links:
      - neo4j
    depends_on:
      - neo4j
    networks: 
      - backend


  authentication-service:
    container_name: authentication-service
    build: ./services/auth/
    ports:
      - "3030:3030"
    links:
      - account-service
      - mongo
    depends_on:
      - mongo
    networks: 
      - backend


  gateway-service:
    container_name: gateway-service
    build: ./services/gateway
    ports:
      - "3010:3010"
    links:
      - account-service
      - authentication-service
    depends_on:
      - authentication-service
      - account-service
    networks: 
      - backend
    environment:
      - AUTH_SERVICE_NAME=authentication-service
      - AUTH_SERVICE_PORT=3030
      - ACCOUNT_SERVICE_NAME=account-service
      - ACCOUNT_SERVICE_PORT=3000

networks:
  backend:
    driver: "bridge"