version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
        - "7474:7474"
        - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import

  account-service:
    container_name: account-service
    build: ./services/account/
    ports: 
      - "3001:3000"
    links:
      - neo4j