version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
        - "7474:7474"
        - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/mongo/

  account-service:
    container_name: account-service
    build: ./services/account/
    ports: 
      - "3000:3000"
    links:
      - neo4j
    depends_on:
      - neo4j

  authentication-service:
    container_name: authentication-service
    build: ./services/auth/
    ports:
      - "3030:3030"
    links:
      - account-service
      - mongo
    depends_on:
      - mongo